### send Data DEV New York
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 40.748817,
    "longitude": -73.985428,
    "temperature": -20,
    "brightness": 4,
    "population": 4,
    "colorscheme": "Normal",
    "style": "realistic"
}

### send Data DEV Zürich
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 47.3769,
    "longitude": 8.5417,
    "temperature": 25,
    "brightness": 3,
    "population": 3,
    "colorscheme": "Normal",
    "style": "realistic"
}

### send Data DEV FELI Züri
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 47.39530,
    "longitude": 8.52969,
    "temperature": 40,
    "brightness": 4,
    "population": 6,
    "colorscheme": "Normal",
    "style": "realistic"
}


### send Data DEV Dettenried
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
  "latitude": 47.4406141,
  "longitude": 8.7772124,
  "temperature": 35,
  "brightness": 5,
  "population": 1,
  "colorscheme": "Normal",
  "style": "realistic"
}



### send Data DEV Paris Eifeltower
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
  "latitude": 48.8588852,
  "longitude": 2.2933869,
  "temperature": -5,
  "brightness": 6,
  "population": 4,
  "colorscheme": "Normal",
  "style": "futuristic"
}


### send Data DEV Winterthur
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
  "latitude":  47.499950,
  "longitude": 8.737565,
  "temperature": -10,
  "brightness": 3,
  "population": 6,
  "colorscheme": "BlackAndWhite",
  "style": "realistic"
}


### send Data DEV Belgrad 44.771291151733635, 17.19130029217816
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
  "latitude":  44.771291,
  "longitude": 17.191300,
  "temperature": 20,
  "brightness": 4,
  "population": 6,
  "colorscheme": "Normal",
  "style": "futuristic"
}

### get History
GET http://127.0.0.1:5000/history HTTP/1.1

### send Data PROD simply the best
POST https://lens-less.azurewebsites.net/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 47.3769,
    "longitude": 8.5417,
    "temperature": -7,
    "brightness": 3,
    "population": 3,
    "colorscheme": "Normal",
    "style": "realistic"
}