### send Data DEV New York
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 40.748817,
    "longitude": -73.985428,
    "temperature": 25,
    "brightness": 3,
    "population": 4,
    "colorscheme": "colourfull",
    "style": "futuristic"
}

### send Data DEV Zürich
POST http://127.0.0.1:5000/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 47.3769,
    "longitude": 8.5417,
    "temperature": 25,
    "brightness": 3,
    "population": 3,
    "colorscheme": "colourfull",
    "style": "realistic"
}

### upload picture
POST http://127.0.0.1:5000/picture HTTP/1.1
Content-Type: multipart/form-data

# Beispiel einer Datei zum Hochladen. Hier müssen Sie den tatsächlichen Dateipfad angeben.
< pictures/test.png

### download picture
GET http://127.0.0.1:5000/picture/<picture_id> HTTP/1.1

### send Data PROD
POST https://lens-less.azurewebsites.net/data HTTP/1.1
Content-Type: application/json

{
    "latitude": 40.748817,
    "longitude": -73.985428,
    "temperature": 25,
    "brightness": 3,
    "population": 4,
    "colorscheme": "colourfull",
    "style": "realistic"
}